### ISSUE TITLE
If you need some nice PR's - go here.

### ISSUE THREAD

**Issue by mio-moto** [steamDBLitter/HacktoberfestPRs#1]
I need help. Pls make gud website. Verry fast. Webscale. Batteries included. 4free - you git 0.5% earnings if successful. 

Edit: Dank Memes appreciated.

**Comment by dehowef** [comment]
Is this like a meta joke

**Comment by ivannieto** [comment]
Keta joke

**Comment by dthlim** [comment]
Opened up #26 to bring everything together. Who needs branches?

**Comment by s-bridges** [comment]
Here is a easy one too https://github.com/s-bridges/Hacktoberfest-Sign-In-2018
